### ISSUE TITLE
[ZS] Trapping zombies inside props taller than them

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#114]
Cheap tactic, props which are taller than the zombie, can be used to nail them into.

Jumping out of the nailed props doesn't work when you're nailed into props which are taller than yourself.

Detrimental to the zombie team if the trapped player was a boss zombie.

**Comment by Raox2** [comment]
Make so nailing prop into a penetrating zombie makes it temp nocollide I guess?

**Comment by BoXiousNet** [comment]
>[Fixed being able to move props or deployables through zombies.](https://forum.noxiousnet.com/topic/13373/publish-408)
It would be the full fix for this, if it did that.
