### ISSUE TITLE
[ZS] Props with 1 repair point remaining unable to be repaired until damaged again

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#115]
Carpenter's Hammer, and Repair field emitter, are both unable to repair the nailed prop if it has 1 repair point currently remaining, until it receives damage again.

Repair field emitters wastes pulse ammo continuously repairing a prop that's unable to be repaired as of this bug.

**Comment by Raox2** [comment]
It's like getting stuck on 0.00000001 barricade repairs. Just need to figure out how to properly clean this up in both the case of the repair field and hammer.
