### ISSUE TITLE
[ZS] Helios Gluon Gun can uncorrupt Sanity Sigils

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#116]
https://forum.noxiousnet.com/topic/14536/publish-420-return-of-nox-rp/41

**Comment by Raox2** [comment]
Crossbow can too.

**Comment by Raox2** [comment]
Restricted to the melee damage types.

**Comment by BoXiousNet** [comment]
Just to make sure, will the poison projectiles from Poison Zombie and Pukepus still able to damage after this?

**Comment by BoXiousNet** [comment]
I know this issue was only regarding the uncorruption of sigils, however is the fix restricted to the Human team? I only ask because Poison Zombies and Pukepus use projectile attacks to damage and corrupt sigils.

**Comment by Raox2** [comment]
any case where they need to damage with poison is a sigil that should be removed

**Comment by JetBoom** [comment]
Zombies should be able to damage with whatever they have. The update doesn't change that.
