### ISSUE TITLE
[ZS] Nightmare's ambience causes FPS lag outside of PAS

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#12]
The looping sound that the Nightmare's ambience plays, causes fps lag outside of your potential audible set.

Using +showbudget, 1 Nightmare can cause the cost of sound to spike by an average of 5ms.
This cost can stack up, to 15ms if 3 Nightmares were spawned.

**Comment by JetBoom** [comment]
See if it's okay now.

**Comment by BoXiousNet** [comment]
It's ok now. thanks.
