### ISSUE TITLE
[ZS] Distance of giving items doesn't match alt menu lock-on

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#122]
I've noticed that you can still be locked onto a player, and the gamemode will think there's no one there.

**Comment by Raox2** [comment]
It's not always going to match since there's 2 different methods of detection at play currently.

**Comment by Raox2** [comment]
Some reason the ValidMenuLock doesn't seem to match up or the angle of lock might not be rotating fast enough. Hard to properly replicate it.

**Comment by BoXiousNet** [comment]
Have the target move around.

**Comment by Raox2** [comment]
It's probably the lock speed then

**Comment by Raox2** [comment]
Gonna close this, there's the message indicator for who you're giving items to and I upped the rotation speed a little.
