### ISSUE TITLE
[ZS] Owner of Drone/Turret unable to see their tracer if another is in view

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#125]
I know the limit of 1 is intentional, however, the owner should always be able to see their own.

**Comment by Raox2** [comment]
Where was it quoted the limit of 1 is intentional? I have a fix which allows you to see all turret tracers while retaining the same 1 second caching.

Also drone tracers seemed to work fine anyway.

**Comment by BoXiousNet** [comment]
Nowhere, it was an assumption.
