### ISSUE TITLE
[ZS] Some models not downloading

### ISSUE THREAD

**Issue by Mark9013100** [JetBoom/noxiousnet-issues#135]
Weapons such as the hammer, sledge hammer, and Annabelle rifle have no first person model and show up as errors. This seems to occur for anyone who hasn't downloaded the gamemode's resources beforehand, however, every time I reconnect to the server, I'm forced to download the missing models again. Will attempt to get screenshots later on.

**Comment by Raox2** [comment]
Apparently, this is to do with case sensitivity for certain gamemode files. Might need to lower case all these.

**Comment by JetBoom** [comment]
they're already lowered, it was something to do with the downloadurl
