### ISSUE TITLE
[ZS] Prop rotation is over-responsive on high ping

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#138]
The higher the player's ping the more they lose control of prop's rotation.
Mouse input becomes over-responsive.

**Comment by Raox2** [comment]
I think this is more a detail of implementation.

**Comment by BoXiousNet** [comment]
Is it not possible to have a clamp?

**Comment by Raox2** [comment]
A clamp on the amount of rotation?

**Comment by JetBoom** [comment]
It's a bad implementation but shouldn't be amazingly hard to change. Right now it uses a console command to send the server an amount of rotational "power". That in of itself is horrible, but it should at the very least be sending a desired rotation rather than a desired rotation rate.
