### ISSUE TITLE
[ZS] trigger_zombieclass for fresh dead will use wraith/bloated zombie model

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#139]
If you were a Wraith or Bloated Zombie and you walked through a trigger_zombieclass brush set to instantly change you to fresh dead, 
you will turn into a fresh dead using the Wraith/Bloated Zombie model for the remainder of that life.

Example maps, zs_obj_6_nights_v8 and zs_obj_dump_v12

**Comment by Raox2** [comment]
Can't replicate this

**Comment by BoXiousNet** [comment]
On the supermarket section, https://www.youtube.com/watch?v=gEbmVy32ECY
