### ISSUE TITLE
[Core] Random map time has a chance to replay recently voted maps

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#140]
On zs, there's been times where the players vote unfavorable maps, and a couple of maps later when it becomes random map time, we end up on the map we played not too long ago.

If random map time could ignore maps in yellow that would be great.

**Comment by BClark09** [comment]
This would the chance of getting an unfavourable map when players don't vote for them?

**Comment by BoXiousNet** [comment]
Sounds about right, but on the off chance a least voted map was voted for, random map time still has a chance to take players back to that same map, couple of maps later.
It's kind of an annoyance to the players in general.

**Comment by BClark09** [comment]
Since the map is shown as recently played after a random map cycle, I guess this would be fine to change.
