### ISSUE TITLE
[ZS] Normal Zombie will repeatedly 2nd wind, if damage source was trigger_hurt

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#144]
zs_obj_vertigo_v23 (5 damage per tick), and zs_obj_lambdacorev16
Use trigger hurts which don't instantly kill the zombies

trigger_hurts that damage the Normal Zombie down to 0 HP, will end up reviving, and then hurt in a repeated manner.

**Comment by Raox2** [comment]
On semi related note it's possible to force yourself to become a torso/legs from suiciding/trigger_hurt etc.

Probably should make it so, only enemy players can force these states to occur since that's when it matters and should come into play.
