### ISSUE TITLE
[ZS] Classes unlocked via logic_classunlock or by infliction, appear locked on F3 menu

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#147]
Zombie classes which are unlocked via logic_classunlock will still appear locked, but useable.

Classes unlocked by infliction rate, like the Fast Zombie, appears locked, but still useable.

On certain maps like zs_obj_enervation_v16, after wave 1 intermission the waves system is disabled, but the wave 2 classes appear unlocked.

**Comment by Raox2** [comment]
Need some way to properly define what is locked and unlocked and network that.
