### ISSUE TITLE
[ZS] Currently selected class to respawn as, doesn't update quick enough

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#149]
If you were killed by a human or ran kill command, and then switched class before respawning, 
clicking on LMB as quick as possible on both the class selection and to respawn, it will still spawn you as the previous class, despite the message pop-up for "You will spawn as a x_class"

**Comment by BoXiousNet** [comment]
Now that I think about it, it could be associated with server lag, it doesn't happen on low player count.

**Comment by BoXiousNet** [comment]
Edited OP

**Comment by Raox2** [comment]
@JetBoom are concommands just slow or something? Only time I see this happen (and can replicate) is when the server is under a decent load from player count.
