### ISSUE TITLE
[ZS] Manhacks can get stuck in between world

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#164]
Dependent on the angle of connecting walls, the manhack can get stuck.

example on zs_riften_v2, the roof meets with the map's ceiling
http://images.akamai.steamusercontent.com/ugc/250339770646755447/B508A58B352F6A68223B7683A7C338B07DED00CF/

I think it's more to do with their hull not being box shaped?

**Comment by Raox2** [comment]
It's trying to move up to account for the hover. I'll make it do two traces for low ceilings.

**Comment by BoXiousNet** [comment]
On, zs_krusty_krab_large_v5
Manhacks can get stuck in between the [static container prop and world](http://images.akamai.steamusercontent.com/ugc/250339770648060392/D6DEA9189830CB7842AF7B1FF5FE183FC92D18F3/).

**Comment by ritzbits** [comment]
close？

**Comment by Raox2** [comment]
Agreed for now.
