### ISSUE TITLE
ZS_countryside

### ISSUE THREAD

**Issue by Wartels** [JetBoom/noxiousnet-issues#171]
Nest do not work 50 % of the time, and for me none of my nest worked at all for the whole game. they are built but no zombies including myself will spawn from them.

**Comment by Raox2** [comment]
>for me none of my nest worked at all for the whole game

So other nests were working and they're closer?! This isn't helpful for replication.

**Comment by BoXiousNet** [comment]
It could be something wrong nests built on displacements.

**Comment by Wartels** [comment]
No my nest was the only ones up, i had 2 at once and no they did not work. The first time i saw a nest working was on round 6 by somone else.
