### ISSUE TITLE
[EFT] Spectating the ball causes the camera to become permanently tilted

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#174]
Spectating the ball, and then switching target leaves the camera view angles permanently tilted.

**Comment by BClark09** [comment]
FYI collaborators cannot edit the EFT code. Are all these EFT issues specific to the version hosted on NxN only?

**Comment by BoXiousNet** [comment]
They are not.

I'm choosing to post them here rather than the public version because I don't think I'll ever see it being updated as frequently as the private version.

**Comment by JetBoom** [comment]
EFT is a mirror copy in terms of updates.

**Comment by BoXiousNet** [comment]
Can collaborators have access to commit updates to the eft gamemode? if it hasn't been done already.

There's so many features which have been on the old publish queue which would be really cool if implemented.

**Comment by BClark09** [comment]
There's no need if it's a carbon copy. Create these issues on JetBoom/extremefootballthrowdown and someone (not just collaborators) can make a pull request into it.

**Comment by BoXiousNet** [comment]
Uh nevermind then.
