### ISSUE TITLE
[ZS] Prop HP display considers owner DEAD if they survived the round via escape door

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#18]

**Comment by JetBoom** [comment]
For all intents and purposes aren't they though?

**Comment by BoXiousNet** [comment]
I think it'd make more sense to make them unclaimed, otherwise it's not a bothersome issue.

**Comment by JetBoom** [comment]
That's pretty much what the (DEAD) indicator does.
