### ISSUE TITLE
[ZS] Remantler +use range too high

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#181]
The range to use a remantler is too excessive.

It works even if the remantler is behind you, when you were meaning to use a resupply infront.

**Comment by Raox2** [comment]
This bug isn't exactly how you think it is.

The remantler is a rescaled model, so it's using the normal scale model for use traces. There's no set use range or anything like that.

**Comment by BoXiousNet** [comment]
Thanks for correcting my misunderstanding.
