### ISSUE TITLE
[ZS] Certain props barely visible when picked up

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#192]
https://github.com/JetBoom/noxiousnet-issues/issues/42

zs_portal_v3 - models/props/lab_chair/lab_chair.mdl

zs_chernobyl_v3 - models/razor/bo4ka01.mdl and models/razor/bo4ka02.mdl

zs_siege_v6 - models/items/item_item_crate.mdl

**Comment by BoXiousNet** [comment]
#42

**Comment by Raox2** [comment]
Not that simple.
