### ISSUE TITLE
[ZS] Muzzle flashes are mislocated on cs:s based weapons

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#196]
https://github.com/JetBoom/noxiousnet-issues/issues/83

https://noxiousnet.com/update/d56f5dd64ecdacf86d68ba4c26b6463d32477535

**Comment by Raox2** [comment]
Guess I'll enable brass ejections huh

**Comment by BoXiousNet** [comment]
No, I'm sure they can be separately toggled.

**Comment by Raox2** [comment]
whatever I did to disable brass ejections fucked with muzzle flashes.

**Comment by BoXiousNet** [comment]
Could you make it so 3rd person muzzle flashes are disabled when the player's weapon doesn't render?
