### ISSUE TITLE
[ZS] Fast Zombie Legs and Torso spawn chance is nil

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#20]
The chance for a fast zombie to turn into fast legs/torso is nil.

**Comment by Raox2** [comment]
http://i.imgur.com/l7Cgper.jpg

Since fast zombies don't have leg hitboxes, it's not going to happen in the current state. I could just remove the check for it/reduce chance to compensate. Not sure.
