### ISSUE TITLE
[ZS] Poison Headcrab RELOAD, plays scream, freezes and then performs primary attack

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#202]

**Comment by Raox2** [comment]
It's actually a way to do a more silent attack at the cost of a longer delay.

**Comment by BoXiousNet** [comment]
That makes no sense.

https://noxiousnet.com/update/a018d9d7b296a8163e0fc97265ab539e5a0abfb4

You marked this issue invalid and closed it but still made a change here, what was it?

**Comment by Raox2** [comment]
what?

**Comment by BoXiousNet** [comment]
To rephrase, 

After marking this issue invalid and closing,
You had still made a change made [here](https://noxiousnet.com/update/a018d9d7b296a8163e0fc97265ab539e5a0abfb4) (to weapon_zs_poisonheadcrab/shared.lua) with no note regarding it.

At the time, I was curious to know what the change was, but, now it doesn't matter, as of this later [change](https://noxiousnet.com/update/6797be5c3429bb584d0c135df5600f65431de8be).
