### ISSUE TITLE
[Core] View player stats and awards results in 404

### ISSUE THREAD

**Issue by puddingking3** [JetBoom/noxiousnet-issues#210]
since site switch (8/04/2016) view player stats and awards displays an error404

```
Error

404: Page not Found
 back
```

**Comment by BoXiousNet** [comment]
https://github.com/JetBoom/noxiousnet-issues/issues/117

**Comment by Raox2** [comment]
works directly on the website rankings page, but through the ingame lookup apparently (viewing someones profile ingame)
