### ISSUE TITLE
[ZS] Dim vision bug

### ISSUE THREAD

**Issue by snipersir** [JetBoom/noxiousnet-issues#220]
This is a rare issue where after the defeat of the survivors before you restart the round hits lurker. Prior to the last second before or during a restart if the time dim view just reached zero and starts to recover normal vision, there is a chance that the respawn of the survivor goes continuation of the clarification of the screen on which it becomes completely white. We have to reconnecting to the server to the problem is gone.

**Comment by Raox2** [comment]
https://github.com/JetBoom/noxiousnet-issues/issues/3
