### ISSUE TITLE
[ZS] Molotov flame doesn't get removed if the owner dies

### ISSUE THREAD

**Issue by Dark-Noob** [JetBoom/noxiousnet-issues#222]
like,grenades and detpack are getting removed too after owner's death. also env_molotovflame killed %username% with env_molotovflame. it steals kills

**Comment by Raox2** [comment]
That's not how it works. I'll just make it not do damage with no owner but it's relatively harmless already since zombies don't get damage credits from it

**Comment by Raox2** [comment]
Grenades and detpacks have their own way of stopping griefing and molotovs are relatively immune as is

**Comment by Dark-Noob** [comment]
Ignited zombies wont't taje damage too?

**Comment by Raox2** [comment]
They already don't post death on entityflame.
