### ISSUE TITLE
[ZS] Zombies can be slowed down when they have spawn protection

### ISSUE THREAD

**Issue by Dark-Noob** [JetBoom/noxiousnet-issues#224]
pretty annoying

**Comment by Raox2** [comment]
What are you talking about? Why not include a way to replicate?

**Comment by Dark-Noob** [comment]
humans can shoot zombies in legs and they get slowed down dunno bout pulse weapons

**Comment by Raox2** [comment]
So why didn't you include the method of replication when you first started the issue? Why did I have to ask for it?

**Comment by Dark-Noob** [comment]
because i'm a stupid russian
