### ISSUE TITLE
[ZS] Weapon Remantler window bug

### ISSUE THREAD

**Issue by zzzaap** [JetBoom/noxiousnet-issues#241]
During heavy lag, spamming E on the weapon remantler will cause two remantling windows to appear. Moving the mouse out of the window only closes one of the two, leaving the second one stuck on the screen.

**Comment by Raox2** [comment]
This one is so hard to replicate you're gonna have to send me a video otherwise I'm never going to know if I've fixed it.

**Comment by zzzaap** [comment]
https://youtu.be/zmF8soGqd8M

**Comment by Raox2** [comment]
Oh wow.
