### ISSUE TITLE
Loading Exoskeleton doesn't have icon and produces errors

### ISSUE THREAD

**Issue by Flairieve** [JetBoom/noxiousnet-issues#255]
I'm not sure if this is on my side but in my weapon selection menu, when I equip the loading exoskeleton tricket, it appears to have no icon and the game gives me this error:

[Zombie Survival] lua/includes/modules/killicon.lua:130: attempt to index field 'color' (a nil value)
  1. Draw - lua/includes/modules/killicon.lua:130
   2. BaseDrawWeaponSelection - gamemodes/zombiesurvival/gamemode/obj_weapon_extend_cl.lua:85
    3. unknown - gamemodes/zombiesurvival/entities/weapons/weapon_zs_basemelee/cl_init.lua:17

Edit: It seems like every tricket icon is bugged for me

**Comment by Raox2** [comment]
It was every trinket, but I've fixed it now.
