### ISSUE TITLE
[ZS] A/An articles in messages

### ISSUE THREAD

**Issue by puddingking3** [JetBoom/noxiousnet-issues#262]
enhancement

agile dead
ammo [...]
eradicator
extinction crab
etc.

![agile dead](https://user-images.githubusercontent.com/10659238/27815136-8419b9e0-6047-11e7-8716-6d06061ca282.PNG)
![insertion feed](https://user-images.githubusercontent.com/10659238/27815137-8426e85e-6047-11e7-92ac-23df509b77ca.PNG)
![ammo](https://user-images.githubusercontent.com/10659238/27815138-8428eeba-6047-11e7-8acc-d0677b3e8532.PNG)
![ancient core](https://user-images.githubusercontent.com/10659238/27815139-842a582c-6047-11e7-9d38-a32f76b2e2a3.PNG)

**Comment by JetBoom** [comment]
"X added to inventory" better wording here.
