### ISSUE TITLE
[ZS] Remove confirmation on dismantling items.

### ISSUE THREAD

**Issue by JetBoom** [JetBoom/noxiousnet-issues#267]
Right now there's an annoying confirmation box to dismantle an item. Shouldn't exist.

**Comment by Raox2** [comment]
Not objecting to it at all, curious as to why you'd want it, I added because I knew someone would accidentally click it, dismantle it and then complain about it.

**Comment by JetBoom** [comment]
we don't need confirmations for buying items so we don't need this.

On Jul 17, 2017 5:07 PM, "James Mountain" <notifications@github.com> wrote:

Not objecting to it at all, curious as to why you'd want it, I added
because I knew someone would accidentally click it, dismantle it and then
complain about it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JetBoom/noxiousnet-issues/issues/267#issuecomment-315884829>,
or mute the thread

**Comment by Raox2** [comment]
I think I need a confirmation for this. People are complaining to me about accidentally dismantling.
