### ISSUE TITLE
[ZS] Drone prop towing function broken/improvements

### ISSUE THREAD

**Issue by puddingking3** [JetBoom/noxiousnet-issues#268]
Drone updated in https://github.com/JetBoom/zombiesurvival-noxiousnet/commit/bbedfd35d20df1e09f64ef2e92ec1ee1d5b86624

Drone **R** cursor function is not working for prop towing or for collecting from resupplies.

The new operation in first person is an improvement, although it could use a HUD with a health and ammunition display, or the ability to switch to third-person operation like the manhack. With the new update, it may also be difficult to tow props while in first person operation.

[enhancement] -- other improvements
It could benefit from an ambient beeping noise as with the HL2 cityscanner to signify drone control is currently active. It's currently silent as it flies through the air. The manhack has an ambient engine grinding noise.

https://www.youtube.com/watch?v=JtnHPNlzCz8

Ambient (_loop_) - either broadcasted from drone or played clientside while in control
npc/scanner/scanner_scan_loop1.wav
npc/scanner/scanner_scan_loop2.wav

Critical Health
npc/scanner/scanner_siren1.wav

Destroyed
npc/scanner/cbot_energyexplosion1.wav
npc/scanner/scanner_explode_crash2.wav

**Comment by Raox2** [comment]
https://steamuserimages-a.akamaihd.net/ugc/849344176027053691/B05BA70346EC66EFA45B49C2305E7C1DC8DF5F97/

All fixed.
