### ISSUE TITLE
[ZS] Force Field placement indicator

### ISSUE THREAD

**Issue by ritzbits** [JetBoom/noxiousnet-issues#282]
https://github.com/JetBoom/zombiesurvival-noxiousnet/commit/4c66a0fe6320c546b3d0766f657f13edd1bf7148
>  Force Field Emitter now deploys the field slightly in front of the emitter base, making it easier to place behind barricades.

Used to deploy in middle of emitter base. It may now require packing up and rotating 180 degrees if it's facing the wrong direction, especially if deployed on the ceiling. No indicator to show which direction is front-facing.

**Comment by Raox2** [comment]
Was wanting to put an arrow on all deployables for their facing angle
