### ISSUE TITLE
[ZS] Remake alt menu - inventory / ammo / craft all in one

### ISSUE THREAD

**Issue by JetBoom** [JetBoom/noxiousnet-issues#285]
Current system is dog shit so I'm gonna redo it all. There's a separate menu for an inventory that only shows trinkets, an ammo menu that looks like shit, and crafting is still bad. It all needs to be consolidated in to a new all-in-one solution. There's three menus and they're all clumsy and slow to use. I'm thinking use the new menu raox made and expand it.

1. Scrap right side of screen menu from holding alt. Holding alt now brings up inventory and nothing else.
2. Inventory shows everything not just trinkets. Weapons, trinkets, ammo, scrap, whatever.
3. Now improve the inventory menu:
* Mouse over to display name, description. Tooltips need to be skinned by the way because they look shit using defaults.
* Can drag things out of inventory to drop them.
* Click on things to do radial context menu. Suppresses tooltips. Depends on what is clicked. Drop (for non-ammo), Drop 1/ Drop all (for ammo), Empty (for guns that hold ammo), etc.
* Weapons should display as a killicon. Other things will need to be a generated silhouette or have ones made for them. Don't want 3d models.
* Ammo will display number in corner.
* Outline color should be the color used on the prop_weapon, prop_ammo whatever dropped on the ground.
4. Now redo crafting.
* All recipes are available as long as you have the materials. No need to find them out.
* Smaller mini-inventory (1 column) lists available crafts that you have materials for. Tooltip is a list of materials when you mouse over. Custom panel here gotta include the icons and stuff.
* Just click once to craft.
* Recipes can now have more than 2 items involved.
* Recipes involving things in the world are removed. Will have to do something about things that require these, probably just make it so pressing use on applicable stuff adds it to inventory. 2 box craft don't care about.
5. Redo dismantling.
* Add dismantle option to radial wheel of items that can be dismantled. If you're not near a Remantler it tells you you have to be near one when you click dismantle.
* Remove dismantle button from Remantler menu.

**Comment by Raox2** [comment]
I'm definitely no interface designer - it was not my strong suit when designing it. I'm looking forward to how it looks concised.

>Add dismantle option to radial wheel of items that can be dismantled. If you're not near a Remantler it tells you you have to be near one when you click dismantle.

So this implies you're going to revert the change where you can dismantle anything anywhere? Because this one was done because: 

1. people cannot pickup multiple weapons (so they can scrap ones they find to pick another).
2. basically associate remantlers with only making things.

Up to you of course.

**Comment by JetBoom** [comment]
If you're not near a Remantler it tells you you have to be near one when you click dismantle.
