### ISSUE TITLE
[ZS] The on-state of other players flashlights spike animations

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#29]
https://www.youtube.com/watch?v=bVilm3jBUBU

The on-state of the engine based flashlight for other players causes lower fps for the client, than usual.
Not specific to this gamemode, but would be beneficial to client performance if replaced with a clientside lua based flashlight.

**Comment by JetBoom** [comment]
Whatever slight loss of perf there is for switching on/off would be off set by the gain from NOT being made in lua.
