### ISSUE TITLE
[ZS] Remantler +USE delay

### ISSUE THREAD

**Issue by ritzbits** [JetBoom/noxiousnet-issues#293]
Remantler owners may encounter a delay in accessing the remantler interface to upgrade or dismantle weapons if scrap is available to collect. If scrap is continually generated, it may take a few seconds to be able to access the remantler interface.

**Comment by Raox2** [comment]
I added this because there was a really weird issue I couldn't replicate where people got stuck in the menu if they pressed too quickly. I'll look for another solution.

**Comment by ritzbits** [comment]
21e5d3ca3491771464c93f09df4633a4aab46e80 | JetBoom/zombiesurvival-noxiousnet | Reduced the delay on using the remantler if your remantler has scrap in it. | Raox2 | 2017-12-28T23:05:52Z
-- | -- | -- | -- | --
