### ISSUE TITLE
[ZS] zs_timelimit & round restart

### ISSUE THREAD

**Issue by ritzbits** [JetBoom/noxiousnet-issues#296]
It may be intended, though the round restart threshold was pushed further back with the reduction in wave 0 time. The actual time for the game remains the same.

`"zs_timelimit" = "15"`
 _- Time in minutes before the game will change maps. It will not change maps if a round is currently in progress but after the current round ends. -1 means never switch maps. 0 means always switch maps._

**Comment by Raox2** [comment]
I don't understand what you're asking to be changed specifically.
