### ISSUE TITLE
[ZS] Shadow Lurker vision debuff persists after death/respawn

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#3]
https://www.youtube.com/watch?v=8FcDnkTQAiI

It also causes the screen to have a white overlay after the debuff duration has expired.
Didn't see a fix for this, so I'm posting it here.

**Comment by BoXiousNet** [comment]
This still happens.

**Comment by Raox2** [comment]
Can't seem to replicate it.

**Comment by BoXiousNet** [comment]
Even if you can't replicate it, can't you make it so the debuff itself is instantly cleaned off on death?

**Comment by Raox2** [comment]
They already are.

**Comment by BoXiousNet** [comment]
And that works 100% of the time?

**Comment by Raox2** [comment]
I don't know but I don't have any concrete replication right now.
