### ISSUE TITLE
[ZS] Biology skill description

### ISSUE THREAD

**Issue by ritzbits** [JetBoom/noxiousnet-issues#303]
Description notes "medic gun effectiveness" although it does affect medical kit. 

May already be in update queue

**Comment by Raox2** [comment]
Technically, medical kits need to be reworked. All Biology does is increase the ammo you can use with the medical kit at a single time.

**Comment by ritzbits** [comment]
725a9ac7f526ed9868b0b16907106ea2d2b7471f | JetBoom/zombiesurvival-noxiousnet | Drone aiming angles slightly increased again. Drones are easy to hit again and creeper nests are really, really easy to make. They also don't destroy them quickly. Force field emitter lua adjustment (but probably is fixed already, just needs server update) Added healing bonuses to remantled medical weapons. Clarified the description on "medical gun effectiveness" to "medical tool effectiveness" | Raox2 | 2018-01-02T19:53:36Z
-- | -- | -- | -- | --
