### ISSUE TITLE
[ZS] OTS 3rd person causes clientside rapid fire and repeated reload animation on fire interrupt

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#39]
https://www.youtube.com/watch?v=jgsFcPBg-nA

The timing of firing and reloading with OTS 3rd person is misleading, because the player is actually still reloading when they interrupt the animation with firing.

Holding Reload and spamming the m1 causes rapid fire on the client.

**Comment by Raox2** [comment]
Fixed
