### ISSUE TITLE
[ZS] Prop translucency makes certain small props invisible

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#42]
Picking up a "models/props_junk/plasticcrate01a.mdl" turns completely invisible.
https://www.youtube.com/watch?v=a7EpTY-_pwg

**Comment by JetBoom** [comment]
Seems some props have an alpha where they just become invisible. I increased it to the threshold for that specific prop.

**Comment by BoXiousNet** [comment]
"models/razor/bo4ka01.mdl" and "models/razor/bo4ka02.mdl" exist on the map zs_chernobyl_v3 also have this issue.

**Comment by BoXiousNet** [comment]
Could there be a 1 solution that fixes all?
I've found other props which are barely visible, zs_siege_v6 uses ammo crates and zs_portal_v1 uses chair props from Portal.
