### ISSUE TITLE
[EFT] Scoreball Bug

### ISSUE THREAD

**Issue by ChiefTuK** [JetBoom/noxiousnet-issues#44]
While the ball is in under the scoreball powerup, if you activate a different powerup, it is activated along with you instantly scoring a touchdown.

Demo: https://www.dropbox.com/s/ogzx165qvfy1t4e/scoreball.dem?dl=0

**Comment by JetBoom** [comment]
Is this from overtime or from powerup triggers?

**Comment by ChiefTuK** [comment]
It's from  a powerup trigger, you can't activate different powerups during overtime
