### ISSUE TITLE
[ZS] Nests placement rules don't work/invalidate on very tight spots or on/between static props

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#51]
http://images.akamai.steamusercontent.com/ugc/1616049762682577414/88BC684D5310DE408E1C8605D2F635DC0F8B6829/

http://images.akamai.steamusercontent.com/ugc/1616049762682577812/E0148605CEB86A938A3027B804E6A71FEA8B86E8/

**Comment by BoXiousNet** [comment]
https://github.com/JetBoom/noxiousnet-issues/issues/69

A nest can be placed within a sigil radius and trap humans within them.
