### ISSUE TITLE
Props unnailed by barricade expert, cannot be renailed by non-experts for 5 seconds

### ISSUE THREAD

**Issue by JetBoom** [JetBoom/noxiousnet-issues#53]
When a person with barricade expert skill, removes the nails of a person without it, that prop will not be ale to be nailed by a non-expert for the next 6 seconds, unless the person who removed the nail is dead or not in the general area during those seconds.

**Comment by BoXiousNet** [comment]
Can you add a message to the center (point_zsmessage) of the owner's hud who removes their nails as it happens?

> [player] removed a nail belonging to you

I know it's on the console/server logs, but a notification which presents itself immediately to you rather than opening the console would be better.

**Comment by Raox2** [comment]
http://i.imgur.com/N4RmSUn.png
