### ISSUE TITLE
[ZS] Duplicating empty prop_weapon of aegis barricade kit from aegis board

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#6]
Deploy all boards from the aegis barricade kit.
Drop the aegis barricade kit, and then proceed to pack a board, deploy the board, and then drop the aegis barricade kit.

This process can be repeated as long as you have 1 aegis board.

While it's harmless, it can still cause an issue where spamming dropped items will invoke the gamemode's cleanup procedure (zs_maxdroppeditems) of prop_weapons/ammo, depriving other players of useful items or ruin their chances of crafting.

**Comment by BoXiousNet** [comment]
I believe the fix for this, would be as simple as stripping the weapon when it's empty, there's no reason to still have it after deploying it's boards.

**Comment by BoXiousNet** [comment]
There's a 2nd method I just learned which should've been part of this fix, if the player is allowed to drop their current barricade kit weapon, they can pack up an aegis board for another.

**Comment by Raox2** [comment]
I might just revert weapon stripping and make it so packing an aegis board only gives you a board ammo. So it acts like a board gun.
