### ISSUE TITLE
Nailing props sometimes leads to being unable to unnail and repair

### ISSUE THREAD

**Issue by bisousbisous** [JetBoom/noxiousnet-issues#64]
Several people have reported that they have been unable to repair or unnail the props that they nail down. For some people there have been no problems but i've seen at least 5 people in chat talk about how they cant repair/unnail anything they nail.

**Comment by puddingking3** [comment]
> All props being held by a human now ignore damage from other humans, and most traces/melee/bullets from all sources pass through them.

A related issue that seems to have come with the latest update are unnailed props becoming unusable to shade once they've been picked up by humans.
