### ISSUE TITLE
[ZS] Prop_ammo model of Rifle is the same as 5.56

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#67]
The worth menu displays Rifle ammo as it's correct model, 
however in the game, the Rifle's prop_ammo is the same as the 5.56

**Comment by BClark09** [comment]
The "correct model" you speak of is an obsolete model, if you tried to change prop_ammo to this the item wouldn't move and you wouldn't be able to pick it up.

**Comment by TheDarkerOne** [comment]
I would recommend using that little cardboard box for rifle ammo models/props_lab/box01a.mdl

**Comment by BClark09** [comment]
Looks good to me, made the swap now.
