### ISSUE TITLE
[ZS] Players can get stuck on prop_creepernest

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#69]
These used to have solid shaped box as their collision, but now they'll suck the human player, if they jumped on it.

**Comment by Raox2** [comment]
Same issue with what I was trying to do with the turret, it seems InitBoxes are plagued currently.

**Comment by BoXiousNet** [comment]
On the public version of zs, this issue doesn't exist, so a change in the private version must've broken it.
