### ISSUE TITLE
[ZS] Manhack's Flashlight color ignores cl_playercolor

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#7]
The Manhack's flashlight ignores the owner's cl_playercolor value.
There was no mention of this change.

The Manhack's sprite however does change color based on the owner's cl_playercolor value.

**Comment by JetBoom** [comment]
Do we really want a disco light show?

**Comment by BoXiousNet** [comment]
haha, ok.
