### ISSUE TITLE
[ZS] Prop's phase pushing even if the prop was nocollide to begin with, or if you were phasing

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#70]
prop_weapon/ammo, these are no collide with players by default, but they'll still push you pick them (with shift+e) and drop them between players.

Another issue is, when you're already phasing through a barricade, and a player sets down a deployable right in front of the cade, this will forcefully attempt to push you back, such issue can lead to your death.

The above also happens if you were phasing into a cade, and a newly nailed prop was added onto the cade.

No-collide deployables like the Repair field emitter, and Zapper, keep the player phased even when there's no need.

**Comment by Raox2** [comment]
I'm not changing the phasing behaviour, but I'll fix everything else.
