### ISSUE TITLE
[ZS] Able to keep phase mode enabled after leaving sigil, with debuff: wide load

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#71]
Players with the debuff: wide load are able to keep the forced phasing from teleporting to a sigil as long as they have +zoom held down.

**Comment by Raox2** [comment]
I don't really see a good solution to this other than to disable using sigils to teleport if you have Wide Load OR making it a huge phasing speed penalty. You cannot force a player into phasing because you can build conduits to said sigil to keep a player phased.

**Comment by Raox2** [comment]
https://forum.noxiousnet.com/topic/14813/zs-clumsy-and-wide-load-reworks
Post here so I know what to do with it

**Comment by Raox2** [comment]
No longer an issue.
