### ISSUE TITLE
[ZS] zs_suicideonclasschange 1 doesn't work on _obj maps.

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#72]
I believe it was an oversight when making the change here.
https://forum.noxiousnet.com/topic/14706/publish-421/57

example map, zs_obj_lambdacoreV16, which doesn't use the wave system when the round begins.

**Comment by BClark09** [comment]
- zs_suicideonchange now works as intended if waves are disabled (Wave End Time < 0 )
