### ISSUE TITLE
[ZS] Prop rotation, specifically the door prop is off-centered

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#73]
Is this the fix that was ignored?
https://forum.noxiousnet.com/topic/13189/zs-re-prop-rotation/20

**Comment by Raox2** [comment]
obbcenter.y * object:GetRight() just needs to be in the opposite direction to account for the incorrect centre of rotation. But I think this issue extends to more than just door props. I seem to recall it being an issue for carts.

**Comment by bisousbisous** [comment]
Also for certain props from junk packs, like the drawer.

**Comment by Raox2** [comment]
Partially fixed for doors.

**Comment by BoXiousNet** [comment]
The drawer model used in the junk pack
>models/props_c17/furnituredrawer001a_chunk02.mdl

Specifically on the map zs_krusty_krab_large_v5
>models/firewavezzmodels/metal_table_test.mdl

Does the fix work on all props with off-centered issue on rotation?

**Comment by Raox2** [comment]
Both of those cases seem to be good now, so I'll close this.
