### ISSUE TITLE
[ZS] Set nailed explosive barrels on fire

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#79]
1. Melee the explosive barrel.
2. Nail it.
3. Melee it again, and it'll ignite.
4. If it survives the above, then you've set up your trap for some unsuspecting player*.

*Provided they were stupid enough to melee a nailed explosive barrel.
It's easier to do this with the carpenter's hammer, as long as it doesn't break on the 1st hit while it's not nailed.

**Comment by puddingking3** [comment]
disclosable information:

You can perform the above by taking an explosive barrel and lowering the prop health to near zero: three punches, or two carpenter's hammer's hits. After that, it can be nailed and destroyed with either melee or bullets. Crafted explosive barrels have less health: one punch and it'll be ready.

**Comment by Raox2** [comment]
Would there be any bad consequence of changing the damage type of a failed CanDamageNail call to DMG_GENERIC from DMG_BULLET? Testing it fixes this issue.
