### ISSUE TITLE
[ZS] Egocentrism affects wave 6 zombie gas

### ISSUE THREAD

**Issue by bisousbisous** [JetBoom/noxiousnet-issues#81]
If you have Egocentrism and the end of wave 6 poison gas spawns you will take GREATLY reduced damaged, around 1hp every hit.

**Comment by BoXiousNet** [comment]
>Commit 2af02123006cc05e1ae90f03671ca96b4c2aaa7a in JetBoom/zombiesurvival-noxiousnet by JetBoom

Fixed TakeSpecialDamage using self instead of world if no attacker defined

**Comment by bisousbisous** [comment]
but ok
