### ISSUE TITLE
[ZS] Insta-kill stove when crouching into it

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#82]
>models/props_c17/furniturestove001a.mdl

Map example: zs_village_v2

This prop can't be picked up, by the Humans or Shade.
It doesn't serve any purpose other than to suicide by crouching into it.

**Comment by BClark09** [comment]
Whilst probably not intended to be a physics prop, the weight of the model is stupidly high. I've reduced it so that it won't harm you.
