### ISSUE TITLE
[ZS] Bullet casings get stuck in team mates

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#83]
http://images.akamai.steamusercontent.com/ugc/1616050420693555389/824CEAF3396882070B3840DF05069EA62B03889E/

**Comment by Raox2** [comment]
Is it possible to actually adjust the way bullet casings actually collide?

**Comment by BoXiousNet** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/client/c_te_legacytempents.cpp#L1642

http://wiki.garrysmod.com/page/WEAPON/FireAnimationEvent

I've noticed that using cl_ejectbrass 0 disables shell ejection, for weapons created by the engine, weapons in sandbox.

In Zombie Survival, this command has no effect.
