### ISSUE TITLE
[ZS] Checking out with more than 1 pistol weapon from worth doesn't give you ammo for both or more

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#86]
Checking out from the worth menu with more than 1 pistol weapon, only gives you the ammo for 1 of those pistol weapons.

**Comment by JetBoom** [comment]
I believe this was intended because it was cheaper to just get a second weapon than some more ammo.

**Comment by BoXiousNet** [comment]
>it was cheaper to just get a second weapon than some more ammo.

I only recall this being a thing back when weapons came with full ammo, but that was fixed by reducing the amount of ammo starting ammo a weapon has and moving most to the ammo tab in worth.

I believe the gamemode has an issue handing ammo stored in the weapons, so rather than combine the ammo, it'll only give you the ammo for 1 weapon.

Players with enough worth to purchase more than 1 pistol type shouldn't lose out this way.

**Comment by JetBoom** [comment]
Why are you purchasing more than one starter of the same type? That makes no sense so there's no reason to "fix" this.

**Comment by BoXiousNet** [comment]
For more pistol ammo, and to stock up on pistol ammo.

A loadout with peashooter, and battleaxe.
The battleaxe I'd give to another player to craft their Waraxe Handgun, and then the peashooter so I can stock up on pistol ammo.

**Comment by Raox2** [comment]
This isn't really a problem but more of a balancing concern, should be discussed as such

**Comment by BoXiousNet** [comment]
There's also another purpose to do this, since we know the gamemode will just eat up ammo stored in guns when crafted, empty the clip.

https://www.youtube.com/watch?v=XprTt7mlweA
