### ISSUE TITLE
[ZS] GM:EntityTakeDamage breaks bosses on ze_ maps

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#87]
>https://forum.noxiousnet.com/topic/14589/zombie-escape-update
init.lua: GM:EntityTakeDamage (line 2223) causes boss entity to break and math counter does not register it as having broken (can be solved by disabling it, but only on ZE maps)

**Comment by puddingking3** [comment]
Boss entities typically use func_physbox to receive damage and it outputs the damage taken to a math_counter. GM:EntityTakeDamage causes entities to take damage and break, this includes func_physbox. After the func_physbox breaks, the math_counter is no longer updated and the post-boss sequence won't be triggered.

**Comment by JetBoom** [comment]
This should be fixed now.

**Comment by BoXiousNet** [comment]
This is the 2nd half of the issue fixed, the 1st half is actually having bullets damage them.
It seems bosses can only be damaged by explosives (ze_grenade), bullets do not work.

ze_gameshow_r1, has an admin room, all 3 levels set to red will start the boss level, this boss doesn't respond to damage from bullets, only grenades.

**Comment by BoXiousNet** [comment]
Well, this may have already been known, but I'd be happy if this was looked at.
https://github.com/JetBoom/zombiesurvival/compare/master...samuelmaddock:ze-fixes

**Comment by BoXiousNet** [comment]
Best to wait and see how ze goes once this branch is done with most/all the issues.
https://github.com/JetBoom/zombiesurvival/compare/master...samuelmaddock:ze-fixes

**Comment by puddingking3** [comment]
The branch mentioned above should fix a lot of outstanding issues some ZE maps currently have. A number of custom map weapons in FFVII Mako Reactor aren't able to be picked up due to func_physbox_multiplayer still remaining despite there being a map profile to remove them; and the bosses should be able to take damage with the given CSS bullet fix.

**Comment by Raox2** [comment]
All issues related to EntityTakeDamage on ZE should be resolved now.
