### ISSUE TITLE
[ZS] Gray font in White combo boxes

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#89]
http://images.akamai.steamusercontent.com/ugc/1616050772325172745/268041A10339313F6D488279EA7D2E2AB24CD364/

It was in the queue long ago, but never fixed.
>https://forum.noxiousnet.com/topic/2081/publish-queue
Fixed the text in comboboxes (dropdown boxes) to be black on white instead of white on white.

**Comment by BClark09** [comment]
- Dropdown menu text is now black instead of white on white.

**Comment by BoXiousNet** [comment]
I forgot this myself, but please fix the black font value for the sliders.
