### ISSUE TITLE
[ZS] Unable to nail func_physbox, if their keyvalue for health is 0

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#92]
Example map, zs_obj_lambdacorev16
http://images.akamai.steamusercontent.com/ugc/261593429779396957/2ED0496D1E9AD6AAFC95A25F08C54E44B0FF08C1/

If the func_physbox doesn't have a health value, then they're unable to be nailed.

Setting their health >0 allows func_physbox to be nailed, http://images.akamai.steamusercontent.com/ugc/261593429779438693/1728D122FD0D3FBDC7674588B6A4A98343F4E334/

**Comment by JetBoom** [comment]
We should let invulnerable physboxes be nailed?

**Comment by BoXiousNet** [comment]
The nailing system would give them health scaling, but even then func_physboxes shouldn't be invulnerable in their unnailed state when they can be carried and used as barricading objects.

**Comment by BClark09** [comment]
It's a rather large oversight for a map developer to not give something intended to be used as a barricade health. Are there any more examples where this is a problem?

**Comment by BClark09** [comment]
This is an issue with specific maps. My worry here is that we try to implement something and we'll break a map that wanted to have an invulnerable physbox.

This should be handled by the person making the map for ZS.

> Are there any more examples where this is a problem?

**Comment by Raox2** [comment]
That's fair enough.

**Comment by BClark09** [comment]
If there any maps which people *think* should have a breakable prop, like zs_obj_lambdacorev16, then I can adjust the server-side version.
