### ISSUE TITLE
[ZS] Death fog sequence causes CUtlLinkedList overflow! (exhausted index range) (65535)!

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#94]
The issue never really went away,
https://forum.noxiousnet.com/topic/14300/publish-417-return-of-the-publishes/125

It's become a common part of zs gameplay to also have to _survive_  game crashes whenever the death fog hits, of course I'm aware escaping gives us the XP and silver.

The chances of this occurring is on high player counts, specific maps, or a combination of both.
Example map: zs_the_house_of_doom
https://forum.noxiousnet.com/topic/14536/publish-420-return-of-nox-rp/87

**Comment by BoXiousNet** [comment]
zs_countryside_b1
https://noxiousnet.com/logs/localhost_27015/2016_08_18/log054.txt
http://steamcommunity.com/sharedfiles/filedetails/?id=747244347

**Comment by BoXiousNet** [comment]
https://www.youtube.com/watch?v=SVetKlIK8CM

**Comment by JetBoom** [comment]
I'm gonna just remove the particles for now then.
