### ISSUE TITLE
[ZS] Helios Gluon Gun unusable if given by another player

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#95]
Given the Helios Gluon Gun by another player, even with ammo, acts as though it has no ammo when holding the primary attack.

The player who has received this weapon, has to reload it.

**Comment by BoXiousNet** [comment]
Hunter Rifle is also unusable if given by another player, reloading doesn't work, they have to drop the weapon and reloading will work.

**Comment by Raox2** [comment]
Fixed the Gluon issue alongside the Gluon rework.
