### ISSUE TITLE
[ZS] Stone in inventory and picking a Stone, consumes it

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#99]
When you have the Stone already in your inventory, picking any dropped on the map, will consume the stone and doesn't add it as ammo.

The player has to use empty clip while wielding the stone, and drop it, before picking any on the map to have multiple stones in their inventory.

**Comment by BClark09** [comment]
This will happen with any weapon who's ammo is essentially itself. A few thoughts,

- You shouldn't be able to "empty" the clip of a weapon such as a stone or grenade.
- Picking up ammo should give you the weapon if you don't have it.
- You shouldn't be able to drop one of these weapons, only as ammo.

**Comment by Raox2** [comment]
I think what needs to happen is to ensure prop_weapon has ammo in it's clip when it is spawned if it is AmmoIfHas, right now they have 0 clip.

**Comment by Raox2** [comment]
"You shouldn't be able to "empty" the clip of a weapon such as a stone or grenade." and "Stone in inventory and picking a Stone, consumes it" are resolved now.
